### ISSUE TITLE
Bit of help needed

### ISSUE THREAD

**Issue by gbkwiatt** [wbu/drawer_organizer#1]
Hi, First of all, awesome design, I like that it can be easily customized. 

About customisation, because I am new to cad, can you please give me a hint, on how to generate dividers only ? 
I can see how to change height of all connectors, also I can see option for divider width, but I can' see divider  itself, and ideally I would like to just generate some dividers with desired length. Can you please assist me with that ?

**Comment by wbu** [comment]
I am not sure, if I understand your question. Are you using OpenSCAD on your computer or the thingiverse customizer?
Anyway, you should be able to create dividers in any length with the following settings:

```
/* [Global Parameters] */

part = "divider";

/* [Divider Settings] */
divider_length = 72;
```

You may have to uncollapse the "Divider Settings" to see the parameters in this section.

I hope this helps.

**Comment by gbkwiatt** [comment]
Thank you, I literally just figured it out myself. But thanks anyway. Awesome job once again

**Comment by wbu** [comment]
Ok, great.

Have fun printing it!
