### ISSUE TITLE
Divider piece

### ISSUE THREAD

**Issue by Tibi-rvb** [wbu/drawer_organizer#16]
For sure I'm doing something wrong but can't seem to find in the .scad file the divider piece.

<img width="905" alt="image" src="https://github.com/wbu/drawer_organizer/assets/75758815/ed7d41c9-761e-471d-affe-66bb77e91b66">

**Comment by wbu** [comment]
You have to set the "part" parameter to "divider" to create dividers. Usually people want to create single piece .stl files and not split the stl files in their slicer. So this is they "standard" way of doing this in openscad and the thingiverse customizer. See https://customizer.makerbot.com/docs for details.

**Comment by Tibi-rvb** [comment]
Totally right, being new to OpenSCAD I was trying to find the piece in the initial screen, just like Sketchup. Thank you ! The divider system is awesome, I've used it for PAX drawers, kitchen drawers, desk drawers ... almost anything.

**Comment by wbu** [comment]
Alright. I am glad you like it. Feel free to add a make to thingiverse or printables!
