### ISSUE TITLE
Rounded border T connector slices badly in PrusaSlicer

### ISSUE THREAD

**Issue by mapfeld** [wbu/drawer_organizer#4]
When slicing the rounded t-connector for borders, the slicer cuts off the lower proportion of the object.
![badly sliced connector](https://user-images.githubusercontent.com/67143206/113731768-527ed900-96f9-11eb-9e8c-609ff54cd65e.png)
As I am not a OpenSCAD expert, I only found a dirty walkaround (line 482 following of the original code, code differs in the difference function):

```
module connector_t_border(round=true) {
    connector_straight(border=true);
    rotate([0,0,90]) {
        translate([0,0.5*connector_length+border_overhang,0]) {
            fitting(male=true);
            intersection() {
                profile(connector_length+border_overhang);
                skew = border_overhang;
                max_radius = max(radius_top,radius_bottom);
                multmatrix(m=[
                    [1,0,0,-max_radius],
                    [0,1,-skew/height,-0.5*connector_length],
                    [0,0,1,0],
                    [0,0,0,1]]) {
                    cube([2*max_radius,connector_length+skew,height]);
                }
            }
        }
    }
    if (round) {
        skew = border_overhang;
        difference() {
            multmatrix(m=[
                [1,0,skew/height,-border_overhang],
                [0,1,0,0],
                [0,0,1,0],
                [0,0,0,1]]) {
                    for (r=[90, 180]) {
                        rotate([0,0,r]) {
                            profile_corner(round=false, border=false);
                        }
                    }
                }
            multmatrix(m=[
                [1,0,skew/height,-border_overhang],
                [0,1,0,0],
                [0,0,1,0],
                [0,0,0,1]]) {
                translate([radius_top,-0.6*connector_length,0])
                    cube([radius_bottom,1.2*connector_length,height]);
            }
        }
    }
}
```

**Comment by mapfeld** [comment]
The provided stl works flawlessly. My slic3r is the PrusaSlicer themed version 2.3.0, and OpenSCAD 2019.05.

**Comment by wbu** [comment]
You seem to be using a old version of openscad. Can you try again with the current version? Please also attach your broken stl file.
So far I have no idea what could be wrong. Maybe the behavior of "for" changed in a openscad version? You could try to wrap the for loop with a union like this:
```openscad
union() {
                for (r=[90, 180]) {
                    rotate([0,0,r]) {
                        profile_corner(round=false, border=false);
                    }
                }
}
```

**Comment by wbu** [comment]
PS: could it be, that you have the option `lazy-union` enabled in your openscad settings?

**Comment by wbu** [comment]
After testing various versions of openscad and prusa-slicer, I came to the conclusion, that PrusaSlicer > 2.0.0 does not seem to slice the `connector_t_round_border` anymore. PrusaSlicer 2.0.0 did work for me. Also the stl files on thingiverse did not slice with PrusaSlicer > 2.0.0.

I tried to check the mesh with freecad, which reports a few errors, but I don't really trust freecad here. Currently my best guess is a bug in PrusaSlicer.

**Comment by wbu** [comment]
There seems to be a workaround, that worked for me:
* import the stl file (it won't slice)
* save the project as 3mf file
* open the 3mf file (it will slice!)
I reported this as issue in PrusaSlicer: https://github.com/prusa3d/PrusaSlicer/issues/6325

**Comment by mapfeld** [comment]
Ok wow. Thank you for your passion in finding the cause of this issue! I'm impressed either by your creativity to find the workaround and the weirdness of it! Quick note: this also works for me.

Just for completeness: the union around the for loop did not help, and I was not able to find the lazy_union option. Hence I was not able to try it.

**Comment by mapfeld** [comment]
For those who land here and wonder: According to the prusa3d authors, the issue is fixed but the release has not been included into a release version.

**Comment by wbu** [comment]
Looks like PrusaSlicer 2.4.0 (released on 2021/12/22) finally fixed the issue.
